Add librespot initial-volume option
hassio-addons/addon-spotify-connect pull request #276
Opened 2024-12-06 08:52 UTC by spoetnik

# Proposed Changes

> Add the librespot initial-volume option. On startup, or after a crash, the volume of spotify goed back to default which is not a convenient level. This configurable option lets the user have influence on this level after a startup of this addon

## Related Issues

> Helps to minimize the impact of this one https://github.com/hassio-addons/addon-spotify-connect/issues/274

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2024-12-06 09:16 UTC, spoetnik commented on spotify/config.yaml
> +  initial-volume: 50
resolved in commit [ebd406a](https://github.com/hassio-addons/addon-spotify-connect/pull/276/commits/ebd406a568ba64123297fd058ed482f3e6e0ed69)

2025-02-02 08:56 UTC, wimdebruyn commented
@spoetnik , this will be a great feature.  I see there is a problem with the PR label: Error! This pull request does not contain any of the valid labels: ['breaking-change', 'bugfix', 'documentation', 'enhancement', 'refactor', 'performance', 'new-feature', 'maintenance', 'ci', 'dependencies', 'translations'].  Hopefully that will allow this PR to go through

2025-02-02 11:13 UTC, spoetnik commented
I have no idea how to add a label to my pull request. If someone can give me e hint on that, I will add a label

2025-02-03 04:29 UTC, wimdebruyn commented
@spoetnik , this will help: https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

2025-02-03 20:37 UTC, spoetnik commented
@frenck I don't see the option to add a label to my pull-request. I think the label 'new-feature' would be appropriate. Can you please add the label, and review my pull-request?

Thanks!

2025-02-08 15:04 UTC, frenck requested changes

2025-02-08 15:04 UTC, frenck commented on spotify/DOCS.md
> +recovers from a crash. The behavior depends on the volume backend in use:
The user has no choice in backend used? So I'm not following these instructions really. Could you explain this?

../Frenck

2025-02-09 15:01 UTC, spoetnik commented on spotify/DOCS.md
> +recovers from a crash. The behavior depends on the volume backend in use:
That's from the original Librespot documentation. If there is no choice for the backend, then this part of the instruction is not relevant.
Do you want me to adjust it, and update the merge request?

2025-02-09 22:23 UTC, frenck commented on spotify/DOCS.md
> +recovers from a crash. The behavior depends on the volume backend in use:
Yeah it isn't relevant :)

Please adjust indeed :)

2025-02-12 09:19 UTC, spoetnik commented
Updated the translationfiles to remove the irrelavant default-volume options

2025-02-12 11:08 UTC, frenck approved these changes
Thanks, @spoetnik 👍 

../Frenck

2025-02-12 11:39 UTC, merged